import {
	type ComboboxContentCommonProps as SearchContentCommonProps,
	type ComboboxContentOptions as SearchContentOptions,
	type ComboboxContentProps as SearchContentProps,
	type ComboboxContentRenderProps as SearchContentRenderProps,
	ComboboxContent as Content,
} from "../combobox/combobox-content";
import {
	type ComboboxInputCommonProps as SearchInputCommonProps,
	type ComboboxInputOptions as SearchInputOptions,
	type ComboboxInputProps as SearchInputProps,
	type ComboboxInputRenderProps as SearchInputRenderProps,
	ComboboxInput as Input,
} from "../combobox/combobox-input";
import {
	type ComboboxListboxCommonProps as SearchListboxCommonProps,
	type ComboboxListboxOptions as SearchListboxOptions,
	type ComboboxListboxProps as SearchListboxProps,
	type ComboboxListboxRenderProps as SearchListboxRenderProps,
	ComboboxListbox as Listbox,
} from "../combobox/combobox-listbox";
import {
	type ComboboxPortalProps as SearchPortalProps,
	ComboboxPortal as Portal,
} from "../combobox/combobox-portal";
import {
	type FormControlDescriptionCommonProps as SearchDescriptionCommonProps,
	type FormControlDescriptionOptions as SearchDescriptionOptions,
	type FormControlDescriptionProps as SearchDescriptionProps,
	type FormControlDescriptionRenderProps as SearchDescriptionRenderProps,
	type FormControlErrorMessageCommonProps as SearchErrorMessageCommonProps,
	type FormControlErrorMessageOptions as SearchErrorMessageOptions,
	type FormControlErrorMessageProps as SearchErrorMessageProps,
	type FormControlErrorMessageRenderProps as SearchErrorMessageRenderProps,
	type FormControlLabelCommonProps as SearchLabelCommonProps,
	type FormControlLabelOptions as SearchLabelOptions,
	type FormControlLabelProps as SearchLabelProps,
	type FormControlLabelRenderProps as SearchLabelRenderProps,
	FormControlDescription as Description,
	FormControlErrorMessage as ErrorMessage,
	FormControlLabel as Label,
} from "../form-control";
import {
	type ListboxItemCommonProps as SearchItemCommonProps,
	type ListboxItemDescriptionCommonProps as SearchItemDescriptionCommonProps,
	type ListboxItemDescriptionOptions as SearchItemDescriptionOptions,
	type ListboxItemDescriptionProps as SearchItemDescriptionProps,
	type ListboxItemDescriptionRenderProps as SearchItemDescriptionRenderProps,
	type ListboxItemIndicatorCommonProps as SearchItemIndicatorCommonProps,
	type ListboxItemIndicatorOptions as SearchItemIndicatorOptions,
	type ListboxItemIndicatorProps as SearchItemIndicatorProps,
	type ListboxItemIndicatorRenderProps as SearchItemIndicatorRenderProps,
	type ListboxItemLabelCommonProps as SearchItemLabelCommonProps,
	type ListboxItemLabelOptions as SearchItemLabelOptions,
	type ListboxItemLabelProps as SearchItemLabelProps,
	type ListboxItemLabelRenderProps as SearchItemLabelRenderProps,
	type ListboxItemOptions as SearchItemOptions,
	type ListboxItemProps as SearchItemProps,
	type ListboxItemRenderProps as SearchItemRenderProps,
	type ListboxSectionCommonProps as SearchSectionCommonProps,
	type ListboxSectionOptions as SearchSectionOptions,
	type ListboxSectionProps as SearchSectionProps,
	type ListboxSectionRenderProps as SearchSectionRenderProps,
	Item,
	ItemDescription,
	ItemIndicator,
	ItemLabel,
	Section,
} from "../listbox";
import {
	Arrow,
	type PopperArrowOptions as SearchArrowOptions,
	type PopperArrowProps as SearchArrowProps,
} from "../popper";
import type {
	ComboboxBaseItemComponentProps as SearchRootItemComponentProps,
	ComboboxBaseSectionComponentProps as SearchRootSectionComponentProps,
} from "../combobox/combobox-base";
import {
	type ComboboxControlCommonProps as SearchControlCommonProps,
	type ComboboxControlOptions as SearchControlOptions,
	type ComboboxControlProps as SearchControlProps,
	type ComboboxControlRenderProps as SearchControlRenderProps,
	ComboboxControl as Control,
} from "../combobox/combobox-control";
import {
	type ComboboxHiddenSelectProps as SearchHiddenSelectProps,
	ComboboxHiddenSelect as HiddenSelect,
} from "../combobox/combobox-hidden-select";
import { type ComboboxIconProps as SearchIconProps, ComboboxIcon as Icon } from "../combobox/combobox-icon";
import {
	type ComboboxMultipleSelectionOptions as SearchMultipleSelectionOptions,
	type ComboboxRootCommonProps as SearchRootCommonProps,
	type ComboboxRootOptions as SearchRootOptions,
	type ComboboxRootProps as SearchRootProps,
	type ComboboxRootRenderProps as SearchRootRenderProps,
	type ComboboxSingleSelectionOptions as SearchSingleSelectionOptions,
	ComboboxRoot as Root,
} from "../combobox/combobox-root";
import {
	type ComboboxTriggerCommonProps as SearchTriggerCommonProps,
	type ComboboxTriggerOptions as SearchTriggerOptions,
	type ComboboxTriggerProps as SearchTriggerProps,
	type ComboboxTriggerRenderProps as SearchTriggerRenderProps,
	ComboboxTrigger as Trigger,
} from "../combobox/combobox-trigger";
import type { ComboboxTriggerMode as SearchTriggerMode } from "../combobox/types";

export type {
	SearchArrowOptions,
	SearchArrowProps,
	SearchContentOptions,
	SearchContentCommonProps,
	SearchContentRenderProps,
	SearchContentProps,
	SearchControlOptions,
	SearchControlCommonProps,
	SearchControlRenderProps,
	SearchControlProps,
	SearchDescriptionOptions,
	SearchDescriptionCommonProps,
	SearchDescriptionRenderProps,
	SearchDescriptionProps,
	SearchErrorMessageOptions,
	SearchErrorMessageCommonProps,
	SearchErrorMessageRenderProps,
	SearchErrorMessageProps,
	SearchHiddenSelectProps,
	SearchIconProps,
	SearchInputOptions,
	SearchInputCommonProps,
	SearchInputRenderProps,
	SearchInputProps,
	SearchItemDescriptionOptions,
	SearchItemDescriptionCommonProps,
	SearchItemDescriptionRenderProps,
	SearchItemDescriptionProps,
	SearchItemIndicatorOptions,
	SearchItemIndicatorCommonProps,
	SearchItemIndicatorRenderProps,
	SearchItemIndicatorProps,
	SearchItemLabelOptions,
	SearchItemLabelCommonProps,
	SearchItemLabelRenderProps,
	SearchItemLabelProps,
	SearchItemOptions,
	SearchItemCommonProps,
	SearchItemRenderProps,
	SearchItemProps,
	SearchLabelOptions,
	SearchLabelCommonProps,
	SearchLabelRenderProps,
	SearchLabelProps,
	SearchListboxOptions,
	SearchListboxCommonProps,
	SearchListboxRenderProps,
	SearchListboxProps,
	SearchMultipleSelectionOptions,
	SearchPortalProps,
	SearchRootItemComponentProps,
	SearchRootOptions,
	SearchRootCommonProps,
	SearchRootRenderProps,
	SearchRootProps,
	SearchRootSectionComponentProps,
	SearchSectionOptions,
	SearchSectionCommonProps,
	SearchSectionRenderProps,
	SearchSectionProps,
	SearchSingleSelectionOptions,
	SearchTriggerMode,
	SearchTriggerOptions,
	SearchTriggerCommonProps,
	SearchTriggerRenderProps,
	SearchTriggerProps,
};

export {
	Arrow,
	Content,
	Control,
	Description,
	ErrorMessage,
	HiddenSelect,
	Icon,
	Input,
	Item,
	ItemDescription,
	ItemIndicator,
	ItemLabel,
	Label,
	Listbox,
	Portal,
	Root,
	Section,
	Trigger,
};

export const Search = Object.assign(Root, {
	Arrow,
	Content,
	Control,
	Description,
	ErrorMessage,
	HiddenSelect,
	Icon,
	Input,
	Item,
	ItemDescription,
	ItemIndicator,
	ItemLabel,
	Label,
	Listbox,
	Portal,
	Section,
	Trigger,
});
