import type { Orientation } from "@kobalte/utils";
import {
	MenuCheckboxItem as CheckboxItem,
	MenuGroup as Group,
	MenuGroupLabel as GroupLabel,
	MenuIcon as Icon,
	MenuItemDescription as ItemDescription,
	MenuItemIndicator as ItemIndicator,
	MenuItemLabel as ItemLabel,
	type MenuCheckboxItemCommonProps as NavigationMenuCheckboxItemCommonProps,
	type MenuCheckboxItemOptions as NavigationMenuCheckboxItemOptions,
	type MenuCheckboxItemProps as NavigationMenuCheckboxItemProps,
	type MenuCheckboxItemRenderProps as NavigationMenuCheckboxItemRenderProps,
	type MenuGroupCommonProps as NavigationMenuGroupCommonProps,
	type MenuGroupLabelCommonProps as NavigationMenuGroupLabelCommonProps,
	type MenuGroupLabelOptions as NavigationMenuGroupLabelOptions,
	type MenuGroupLabelProps as NavigationMenuGroupLabelProps,
	type MenuGroupLabelRenderProps as NavigationMenuGroupLabelRenderProps,
	type MenuGroupOptions as NavigationMenuGroupOptions,
	type MenuGroupProps as NavigationMenuGroupProps,
	type MenuGroupRenderProps as NavigationMenuGroupRenderProps,
	type MenuIconCommonProps as NavigationMenuIconCommonProps,
	type MenuIconOptions as NavigationMenuIconOptions,
	type MenuIconProps as NavigationMenuIconProps,
	type MenuIconRenderProps as NavigationMenuIconRenderProps,
	type MenuItemCommonProps as NavigationMenuItemCommonProps,
	type MenuItemDescriptionCommonProps as NavigationMenuItemDescriptionCommonProps,
	type MenuItemDescriptionOptions as NavigationMenuItemDescriptionOptions,
	type MenuItemDescriptionProps as NavigationMenuItemDescriptionProps,
	type MenuItemDescriptionRenderProps as NavigationMenuItemDescriptionRenderProps,
	type MenuItemIndicatorCommonProps as NavigationMenuItemIndicatorCommonProps,
	type MenuItemIndicatorOptions as NavigationMenuItemIndicatorOptions,
	type MenuItemIndicatorProps as NavigationMenuItemIndicatorProps,
	type MenuItemIndicatorRenderProps as NavigationMenuItemIndicatorRenderProps,
	type MenuItemLabelCommonProps as NavigationMenuItemLabelCommonProps,
	type MenuItemLabelOptions as NavigationMenuItemLabelOptions,
	type MenuItemLabelProps as NavigationMenuItemLabelProps,
	type MenuItemLabelRenderProps as NavigationMenuItemLabelRenderProps,
	type MenuItemOptions as NavigationMenuItemOptions,
	type MenuItemProps as NavigationMenuItemProps,
	type MenuItemRenderProps as NavigationMenuItemRenderProps,
	type MenuRadioGroupCommonProps as NavigationMenuRadioGroupCommonProps,
	type MenuRadioGroupOptions as NavigationMenuRadioGroupOptions,
	type MenuRadioGroupProps as NavigationMenuRadioGroupProps,
	type MenuRadioGroupRenderProps as NavigationMenuRadioGroupRenderProps,
	type MenuRadioItemCommonProps as NavigationMenuRadioItemCommonProps,
	type MenuRadioItemOptions as NavigationMenuRadioItemOptions,
	type MenuRadioItemRenderProps as NavigationMenuRadioItemPRenderrops,
	type MenuRadioItemProps as NavigationMenuRadioItemProps,
	type MenuSubContentCommonProps as NavigationMenuSubContentCommonProps,
	type MenuSubContentOptions as NavigationMenuSubContentOptions,
	type MenuSubContentProps as NavigationMenuSubContentProps,
	type MenuSubContentRenderProps as NavigationMenuSubContentRenderProps,
	type MenuSubOptions as NavigationMenuSubOptions,
	type MenuSubProps as NavigationMenuSubProps,
	type MenuSubTriggerCommonProps as NavigationMenuSubTriggerCommonProps,
	type MenuSubTriggerOptions as NavigationMenuSubTriggerOptions,
	type MenuSubTriggerProps as NavigationMenuSubTriggerProps,
	type MenuSubTriggerRenderProps as NavigationMenuSubTriggerRenderProps,
	MenuRadioGroup as RadioGroup,
	MenuRadioItem as RadioItem,
	MenuSub as Sub,
	MenuSubContent as SubContent,
	MenuSubTrigger as SubTrigger,
} from "../menu";
import {
	type SeparatorRootCommonProps as NavigationMenuSeparatorCommonProps,
	type SeparatorRootOptions as NavigationMenuSeparatorOptions,
	type SeparatorRootProps as NavigationMenuSeparatorProps,
	type SeparatorRootRenderProps as NavigationMenuSeparatorRenderProps,
	Root as Separator,
} from "../separator";
import {
	NavigationMenuArrow as Arrow,
	type NavigationMenuArrowCommonProps,
	type NavigationMenuArrowOptions,
	type NavigationMenuArrowProps,
	type NavigationMenuArrowRenderProps,
} from "./navigation-menu-arrow";
import {
	NavigationMenuContent as Content,
	type Motion,
	type NavigationMenuContentCommonProps,
	type NavigationMenuContentOptions,
	type NavigationMenuContentProps,
	type NavigationMenuContentRenderProps,
} from "./navigation-menu-content";
import { NavigationMenuItem as Item } from "./navigation-menu-item";
import {
	NavigationMenuMenu as Menu,
	type NavigationMenuMenuOptions,
	type NavigationMenuMenuProps,
} from "./navigation-menu-menu";
import {
	type NavigationMenuPortalProps,
	NavigationMenuPortal as Portal,
} from "./navigation-menu-portal";
import {
	type NavigationMenuRootCommonProps,
	type NavigationMenuRootOptions,
	type NavigationMenuRootProps,
	type NavigationMenuRootRenderProps,
	NavigationMenuRoot as Root,
} from "./navigation-menu-root";
import {
	type NavigationMenuTriggerCommonProps,
	type NavigationMenuTriggerOptions,
	type NavigationMenuTriggerProps,
	type NavigationMenuTriggerRenderProps,
	NavigationMenuTrigger as Trigger,
} from "./navigation-menu-trigger";
import {
	type NavigationMenuViewportCommonProps,
	type NavigationMenuViewportOptions,
	type NavigationMenuViewportProps,
	type NavigationMenuViewportRenderProps,
	NavigationMenuViewport as Viewport,
} from "./navigation-menu-viewport";

export type {
	Motion,
	NavigationMenuArrowCommonProps,
	NavigationMenuArrowOptions,
	NavigationMenuArrowProps,
	NavigationMenuArrowRenderProps,
	NavigationMenuCheckboxItemCommonProps,
	NavigationMenuCheckboxItemOptions,
	NavigationMenuCheckboxItemProps,
	NavigationMenuCheckboxItemRenderProps,
	NavigationMenuContentCommonProps,
	NavigationMenuContentOptions,
	NavigationMenuContentProps,
	NavigationMenuContentRenderProps,
	NavigationMenuGroupCommonProps,
	NavigationMenuGroupLabelCommonProps,
	NavigationMenuGroupLabelOptions,
	NavigationMenuGroupLabelProps,
	NavigationMenuGroupLabelRenderProps,
	NavigationMenuGroupOptions,
	NavigationMenuGroupProps,
	NavigationMenuGroupRenderProps,
	NavigationMenuIconCommonProps,
	NavigationMenuIconOptions,
	NavigationMenuIconProps,
	NavigationMenuIconRenderProps,
	NavigationMenuItemCommonProps,
	NavigationMenuItemDescriptionCommonProps,
	NavigationMenuItemDescriptionOptions,
	NavigationMenuItemDescriptionProps,
	NavigationMenuItemDescriptionRenderProps,
	NavigationMenuItemIndicatorCommonProps,
	NavigationMenuItemIndicatorOptions,
	NavigationMenuItemIndicatorProps,
	NavigationMenuItemIndicatorRenderProps,
	NavigationMenuItemLabelCommonProps,
	NavigationMenuItemLabelOptions,
	NavigationMenuItemLabelProps,
	NavigationMenuItemLabelRenderProps,
	NavigationMenuItemOptions,
	NavigationMenuItemProps,
	NavigationMenuItemRenderProps,
	NavigationMenuMenuOptions,
	NavigationMenuMenuProps,
	NavigationMenuPortalProps,
	NavigationMenuRadioGroupCommonProps,
	NavigationMenuRadioGroupOptions,
	NavigationMenuRadioGroupProps,
	NavigationMenuRadioGroupRenderProps,
	NavigationMenuRadioItemCommonProps,
	NavigationMenuRadioItemOptions,
	NavigationMenuRadioItemPRenderrops,
	NavigationMenuRadioItemProps,
	NavigationMenuRootCommonProps,
	NavigationMenuRootOptions,
	NavigationMenuRootProps,
	NavigationMenuRootRenderProps,
	NavigationMenuSeparatorCommonProps,
	NavigationMenuSeparatorOptions,
	NavigationMenuSeparatorProps,
	NavigationMenuSeparatorRenderProps,
	NavigationMenuSubContentCommonProps,
	NavigationMenuSubContentOptions,
	NavigationMenuSubContentProps,
	NavigationMenuSubContentRenderProps,
	NavigationMenuSubOptions,
	NavigationMenuSubProps,
	NavigationMenuSubTriggerCommonProps,
	NavigationMenuSubTriggerOptions,
	NavigationMenuSubTriggerProps,
	NavigationMenuSubTriggerRenderProps,
	NavigationMenuTriggerCommonProps,
	NavigationMenuTriggerOptions,
	NavigationMenuTriggerProps,
	NavigationMenuTriggerRenderProps,
	NavigationMenuViewportCommonProps,
	NavigationMenuViewportOptions,
	NavigationMenuViewportProps,
	NavigationMenuViewportRenderProps,
	Orientation,
};

export {
	Arrow,
	CheckboxItem,
	Content,
	Group,
	GroupLabel,
	Icon,
	Item,
	ItemDescription,
	ItemIndicator,
	ItemLabel,
	Menu,
	Portal,
	RadioGroup,
	RadioItem,
	Root,
	Separator,
	Sub,
	SubContent,
	SubTrigger,
	Trigger,
	Viewport,
};

export const NavigationMenu = Object.assign(Root, {
	Arrow,
	CheckboxItem,
	Content,
	Group,
	GroupLabel,
	Icon,
	Item,
	ItemDescription,
	ItemIndicator,
	ItemLabel,
	Portal,
	RadioGroup,
	RadioItem,
	Menu,
	Separator,
	Sub,
	SubContent,
	SubTrigger,
	Trigger,
	Viewport,
});

/**
 * API will most probably change
 */
export {
	type NavigationMenuContextValue,
	useNavigationMenuContext,
} from "./navigation-menu-context";
