import {
  Arrow,
  Content,
  Description,
  ErrorMessage,
  HiddenSelect,
  Icon,
  Item,
  ItemDescription,
  ItemIndicator,
  ItemLabel,
  Label,
  Listbox,
  Portal,
  Section,
  type SelectArrowOptions as MultiSelectArrowOptions,
  type SelectContentOptions as MultiSelectContentOptions,
  type SelectItemIndicatorOptions as MultiSelectItemIndicatorOptions,
  type SelectItemOptions as MultiSelectItemOptions,
  type SelectListboxOptions as MultiSelectListboxOptions,
  Trigger,
  Value,
} from "../select";
import { MultiSelectRoot as Root, type MultiSelectRootOptions } from "./multi-select-root";

export type {
  MultiSelectArrowOptions,
  MultiSelectContentOptions,
  MultiSelectItemIndicatorOptions,
  MultiSelectItemOptions,
  MultiSelectListboxOptions,
  MultiSelectRootOptions,
};

export {
  Arrow,
  Content,
  Description,
  ErrorMessage,
  HiddenSelect,
  Icon,
  Item,
  ItemDescription,
  ItemIndicator,
  ItemLabel,
  Label,
  Listbox,
  Portal,
  Root,
  Section,
  Trigger,
  Value,
};
