import {
  Arrow,
  Content,
  Description,
  ErrorMessage,
  HiddenSelect,
  Icon,
  Item,
  ItemDescription,
  ItemIndicator,
  ItemLabel,
  Label,
  Listbox,
  Portal,
  Section,
  type SelectArrowOptions as MultiSelectArrowOptions,
  type SelectArrowProps as MultiSelectArrowProps,
  type SelectContentOptions as MultiSelectContentOptions,
  type SelectContentProps as MultiSelectContentProps,
  type SelectDescriptionProps as MultiSelectDescriptionProps,
  type SelectErrorMessageOptions as MultiSelectErrorMessageOptions,
  type SelectErrorMessageProps as MultiSelectErrorMessageProps,
  type SelectHiddenSelectProps as MultiSelectHiddenSelectProps,
  type SelectIconProps as MultiSelectIconProps,
  type SelectItemDescriptionProps as MultiSelectItemDescriptionProps,
  type SelectItemIndicatorOptions as MultiSelectItemIndicatorOptions,
  type SelectItemIndicatorProps as MultiSelectItemIndicatorProps,
  type SelectItemLabelProps as MultiSelectItemLabelProps,
  type SelectItemOptions as MultiSelectItemOptions,
  type SelectItemProps as MultiSelectItemProps,
  type SelectLabelProps as MultiSelectLabelProps,
  type SelectListboxOptions as MultiSelectListboxOptions,
  type SelectListboxProps as MultiSelectListboxProps,
  type SelectPortalProps as MultiSelectPortalProps,
  type SelectSectionProps as MultiSelectSectionProps,
  type SelectTriggerProps as MultiSelectTriggerProps,
  type SelectValueProps as MultiSelectValueProps,
  Trigger,
  Value,
} from "../select";
import {
  type MultiSelectItemComponentProps,
  MultiSelectRoot as Root,
  type MultiSelectRootOptions,
  type MultiSelectRootProps,
  type MultiSelectSectionComponentProps,
  type MultiSelectValueComponentProps,
} from "./multi-select-root";

export type {
  MultiSelectArrowOptions,
  MultiSelectArrowProps,
  MultiSelectContentOptions,
  MultiSelectContentProps,
  MultiSelectDescriptionProps,
  MultiSelectErrorMessageOptions,
  MultiSelectErrorMessageProps,
  MultiSelectHiddenSelectProps,
  MultiSelectIconProps,
  MultiSelectItemComponentProps,
  MultiSelectItemDescriptionProps,
  MultiSelectItemIndicatorOptions,
  MultiSelectItemIndicatorProps,
  MultiSelectItemLabelProps,
  MultiSelectItemOptions,
  MultiSelectItemProps,
  MultiSelectLabelProps,
  MultiSelectListboxOptions,
  MultiSelectListboxProps,
  MultiSelectPortalProps,
  MultiSelectRootOptions,
  MultiSelectRootProps,
  MultiSelectSectionComponentProps,
  MultiSelectSectionProps,
  MultiSelectTriggerProps,
  MultiSelectValueComponentProps,
  MultiSelectValueProps,
};

export {
  Arrow,
  Content,
  Description,
  ErrorMessage,
  HiddenSelect,
  Icon,
  Item,
  ItemDescription,
  ItemIndicator,
  ItemLabel,
  Label,
  Listbox,
  Portal,
  Root,
  Section,
  Trigger,
  Value,
};
