import {
  Arrow,
  Button,
  type ComboboxArrowOptions as MultiComboboxArrowOptions,
  type ComboboxArrowProps as MultiComboboxArrowProps,
  type ComboboxButtonProps as MultiComboboxButtonProps,
  type ComboboxContentOptions as MultiComboboxContentOptions,
  type ComboboxContentProps as MultiComboboxContentProps,
  type ComboboxDescriptionProps as MultiComboboxDescriptionProps,
  type ComboboxErrorMessageOptions as MultiComboboxErrorMessageOptions,
  type ComboboxErrorMessageProps as MultiComboboxErrorMessageProps,
  type ComboboxInputProps as MultiComboboxInputProps,
  type ComboboxItemDescriptionProps as MultiComboboxItemDescriptionProps,
  type ComboboxItemIndicatorOptions as MultiComboboxItemIndicatorOptions,
  type ComboboxItemIndicatorProps as MultiComboboxItemIndicatorProps,
  type ComboboxItemLabelProps as MultiComboboxItemLabelProps,
  type ComboboxItemOptions as MultiComboboxItemOptions,
  type ComboboxItemProps as MultiComboboxItemProps,
  type ComboboxLabelProps as MultiComboboxLabelProps,
  type ComboboxListboxOptions as MultiComboboxListboxOptions,
  type ComboboxListboxProps as MultiComboboxListboxProps,
  type ComboboxPortalProps as MultiComboboxPortalProps,
  type ComboboxSectionProps as MultiComboboxSectionProps,
  type ComboboxTriggerProps as MultiComboboxTriggerProps,
  type ComboboxValueProps as MultiComboboxValueProps,
  Content,
  Description,
  ErrorMessage,
  Input,
  Item,
  ItemDescription,
  ItemIndicator,
  ItemLabel,
  Label,
  Listbox,
  Portal,
  Section,
  Trigger,
  Value,
} from "../combobox";
import {
  type MultiComboboxItemComponentProps,
  MultiComboboxRoot as Root,
  type MultiComboboxRootOptions,
  type MultiComboboxRootProps,
  type MultiComboboxSectionComponentProps,
  type MultiComboboxValueComponentProps,
} from "./multi-combobox-root";

export type {
  MultiComboboxArrowOptions,
  MultiComboboxArrowProps,
  MultiComboboxButtonProps,
  MultiComboboxContentOptions,
  MultiComboboxContentProps,
  MultiComboboxDescriptionProps,
  MultiComboboxErrorMessageOptions,
  MultiComboboxErrorMessageProps,
  MultiComboboxInputProps,
  MultiComboboxItemComponentProps,
  MultiComboboxItemDescriptionProps,
  MultiComboboxItemIndicatorOptions,
  MultiComboboxItemIndicatorProps,
  MultiComboboxItemLabelProps,
  MultiComboboxItemOptions,
  MultiComboboxItemProps,
  MultiComboboxLabelProps,
  MultiComboboxListboxOptions,
  MultiComboboxListboxProps,
  MultiComboboxPortalProps,
  MultiComboboxRootOptions,
  MultiComboboxRootProps,
  MultiComboboxSectionComponentProps,
  MultiComboboxSectionProps,
  MultiComboboxTriggerProps,
  MultiComboboxValueComponentProps,
  MultiComboboxValueProps,
};

export {
  Arrow,
  Button,
  Content,
  Description,
  ErrorMessage,
  Input,
  Item,
  ItemDescription,
  ItemIndicator,
  ItemLabel,
  Label,
  Listbox,
  Portal,
  Root,
  Section,
  Trigger,
  Value,
};
