import {
  Arrow,
  type ComboboxArrowOptions as MultiComboboxArrowOptions,
  type ComboboxArrowProps as MultiComboboxArrowProps,
  type ComboboxContentOptions as MultiComboboxContentOptions,
  type ComboboxContentProps as MultiComboboxContentProps,
  type ComboboxDescriptionProps as MultiComboboxDescriptionProps,
  type ComboboxErrorMessageOptions as MultiComboboxErrorMessageOptions,
  type ComboboxErrorMessageProps as MultiComboboxErrorMessageProps,
  type ComboboxHiddenSelectProps as MultiComboboxHiddenSelectProps,
  type ComboboxInputProps as MultiComboboxInputProps,
  type ComboboxItemDescriptionProps as MultiComboboxItemDescriptionProps,
  type ComboboxItemIndicatorOptions as MultiComboboxItemIndicatorOptions,
  type ComboboxItemIndicatorProps as MultiComboboxItemIndicatorProps,
  type ComboboxItemLabelProps as MultiComboboxItemLabelProps,
  type ComboboxItemOptions as MultiComboboxItemOptions,
  type ComboboxItemProps as MultiComboboxItemProps,
  type ComboboxLabelProps as MultiComboboxLabelProps,
  type ComboboxListboxOptions as MultiComboboxListboxOptions,
  type ComboboxListboxProps as MultiComboboxListboxProps,
  type ComboboxPortalProps as MultiComboboxPortalProps,
  type ComboboxSectionProps as MultiComboboxSectionProps,
  type ComboboxTriggerProps as MultiComboboxTriggerProps,
  Content,
  Description,
  ErrorMessage,
  HiddenSelect,
  Input,
  Item,
  ItemDescription,
  ItemIndicator,
  ItemLabel,
  Label,
  Listbox,
  Portal,
  Section,
  Trigger,
} from "../combobox";
import {
  ComboboxControlBase as Control,
  type ComboboxControlBaseProps as MultiComboboxControlProps,
} from "../combobox/combobox-control-base";
import {
  MultiComboboxRoot as Root,
  type MultiComboboxRootItemComponentProps,
  type MultiComboboxRootOptions,
  type MultiComboboxRootProps,
  type MultiComboboxRootSectionComponentProps,
} from "./multi-combobox-root";

export type {
  MultiComboboxArrowOptions,
  MultiComboboxArrowProps,
  MultiComboboxContentOptions,
  MultiComboboxContentProps,
  MultiComboboxControlProps,
  MultiComboboxDescriptionProps,
  MultiComboboxErrorMessageOptions,
  MultiComboboxErrorMessageProps,
  MultiComboboxHiddenSelectProps,
  MultiComboboxInputProps,
  MultiComboboxItemDescriptionProps,
  MultiComboboxItemIndicatorOptions,
  MultiComboboxItemIndicatorProps,
  MultiComboboxItemLabelProps,
  MultiComboboxItemOptions,
  MultiComboboxItemProps,
  MultiComboboxLabelProps,
  MultiComboboxListboxOptions,
  MultiComboboxListboxProps,
  MultiComboboxPortalProps,
  MultiComboboxRootItemComponentProps,
  MultiComboboxRootOptions,
  MultiComboboxRootProps,
  MultiComboboxRootSectionComponentProps,
  MultiComboboxSectionProps,
  MultiComboboxTriggerProps,
};

export {
  Arrow,
  Content,
  Control,
  Description,
  ErrorMessage,
  HiddenSelect,
  Input,
  Item,
  ItemDescription,
  ItemIndicator,
  ItemLabel,
  Label,
  Listbox,
  Portal,
  Root,
  Section,
  Trigger,
};
