import {
  Arrow,
  Button,
  type ComboboxArrowOptions as MultiComboboxArrowOptions,
  type ComboboxArrowProps as MultiComboboxArrowProps,
  type ComboboxButtonProps as MultiComboboxButtonProps,
  type ComboboxContentOptions as MultiComboboxContentOptions,
  type ComboboxContentProps as MultiComboboxContentProps,
  type ComboboxDescriptionProps as MultiComboboxDescriptionProps,
  type ComboboxErrorMessageOptions as MultiComboboxErrorMessageOptions,
  type ComboboxErrorMessageProps as MultiComboboxErrorMessageProps,
  type ComboboxInputProps as MultiComboboxInputProps,
  type ComboboxItemDescriptionProps as MultiComboboxItemDescriptionProps,
  type ComboboxItemIndicatorOptions as MultiComboboxItemIndicatorOptions,
  type ComboboxItemIndicatorProps as MultiComboboxItemIndicatorProps,
  type ComboboxItemLabelProps as MultiComboboxItemLabelProps,
  type ComboboxItemOptions as MultiComboboxItemOptions,
  type ComboboxItemProps as MultiComboboxItemProps,
  type ComboboxLabelProps as MultiComboboxLabelProps,
  type ComboboxListboxOptions as MultiComboboxListboxOptions,
  type ComboboxListboxProps as MultiComboboxListboxProps,
  type ComboboxPortalProps as MultiComboboxPortalProps,
  type ComboboxSectionProps as MultiComboboxSectionProps,
  Content,
  Description,
  ErrorMessage,
  Input,
  Item,
  ItemDescription,
  ItemIndicator,
  ItemLabel,
  Label,
  Listbox,
  Portal,
  Section,
} from "../combobox";
import {
  ComboboxTriggerBase as Trigger,
  type ComboboxTriggerBaseProps as MultiComboboxTriggerProps,
} from "../combobox/combobox-trigger-base";
import {
  MultiComboboxRoot as Root,
  type MultiComboboxRootItemComponentProps,
  type MultiComboboxRootOptions,
  type MultiComboboxRootProps,
  type MultiComboboxRootSectionComponentProps,
} from "./multi-combobox-root";

export type {
  MultiComboboxArrowOptions,
  MultiComboboxArrowProps,
  MultiComboboxButtonProps,
  MultiComboboxContentOptions,
  MultiComboboxContentProps,
  MultiComboboxDescriptionProps,
  MultiComboboxErrorMessageOptions,
  MultiComboboxErrorMessageProps,
  MultiComboboxInputProps,
  MultiComboboxItemDescriptionProps,
  MultiComboboxItemIndicatorOptions,
  MultiComboboxItemIndicatorProps,
  MultiComboboxItemLabelProps,
  MultiComboboxItemOptions,
  MultiComboboxItemProps,
  MultiComboboxLabelProps,
  MultiComboboxListboxOptions,
  MultiComboboxListboxProps,
  MultiComboboxPortalProps,
  MultiComboboxRootItemComponentProps,
  MultiComboboxRootOptions,
  MultiComboboxRootProps,
  MultiComboboxRootSectionComponentProps,
  MultiComboboxSectionProps,
  MultiComboboxTriggerProps,
};

export {
  Arrow,
  Button,
  Content,
  Description,
  ErrorMessage,
  Input,
  Item,
  ItemDescription,
  ItemIndicator,
  ItemLabel,
  Label,
  Listbox,
  Portal,
  Root,
  Section,
  Trigger,
};
