export const BREADCRUMBS_INTL_MESSAGES = {
  "ar-AE": { breadcrumbs: "عناصر الواجهة" },
  "bg-BG": { breadcrumbs: "Трохи хляб" },
  "cs-CZ": { breadcrumbs: "Popis cesty" },
  "da-DK": { breadcrumbs: "Brødkrummer" },
  "de-DE": { breadcrumbs: "Breadcrumbs" },
  "el-GR": { breadcrumbs: "Πλοηγήσεις breadcrumb" },
  "en-US": { breadcrumbs: "Breadcrumbs" },
  "es-ES": { breadcrumbs: "Migas de pan" },
  "et-EE": { breadcrumbs: "Lingiread" },
  "fi-FI": { breadcrumbs: "Navigointilinkit" },
  "fr-FR": { breadcrumbs: "Chemin de navigation" },
  "he-IL": { breadcrumbs: "שבילי ניווט" },
  "hr-HR": { breadcrumbs: "Navigacijski putovi" },
  "hu-HU": { breadcrumbs: "Morzsamenü" },
  "it-IT": { breadcrumbs: "Breadcrumb" },
  "ja-JP": { breadcrumbs: "パンくずリスト" },
  "ko-KR": { breadcrumbs: "탐색 표시" },
  "lt-LT": { breadcrumbs: "Naršymo kelias" },
  "lv-LV": { breadcrumbs: "Atpakaļceļi" },
  "nb-NO": { breadcrumbs: "Navigasjonsstier" },
  "nl-NL": { breadcrumbs: "Broodkruimels" },
  "pl-PL": { breadcrumbs: "Struktura nawigacyjna" },
  "pt-BR": { breadcrumbs: "Caminho detalhado" },
  "pt-PT": { breadcrumbs: "Categorias" },
  "ro-RO": { breadcrumbs: "Miez de pâine" },
  "ru-RU": { breadcrumbs: "Навигация" },
  "sk-SK": { breadcrumbs: "Navigačné prvky Breadcrumbs" },
  "sl-SI": { breadcrumbs: "Drobtine" },
  "sr-SP": { breadcrumbs: "Putanje navigacije" },
  "sv-SE": { breadcrumbs: "Sökvägar" },
  "tr-TR": { breadcrumbs: "İçerik haritaları" },
  "uk-UA": { breadcrumbs: "Навігаційна стежка" },
  "zh-CN": { breadcrumbs: "导航栏" },
  "zh-TW": { breadcrumbs: "導覽列" },
};
