export const DATE_PICKER_INTL_MESSAGES = {
  "ar-AE": {
    calendar: "التقويم",
    day: "يوم",
    dayPeriod: "ص/م",
    endDate: "تاريخ الانتهاء",
    era: "العصر",
    hour: "الساعات",
    minute: "الدقائق",
    month: "الشهر",
    second: "الثواني",
    selectedDateDescription: "تاريخ محدد: {date}",
    selectedRangeDescription: "المدى الزمني المحدد: {startDate} إلى {endDate}",
    selectedTimeDescription: "الوقت المحدد: {time}",
    startDate: "تاريخ البدء",
    timeZoneName: "التوقيت",
    weekday: "اليوم",
    year: "السنة",
  },
  "bg-BG": {
    calendar: "Календар",
    day: "ден",
    dayPeriod: "пр.об./сл.об.",
    endDate: "Крайна дата",
    era: "ера",
    hour: "час",
    minute: "минута",
    month: "месец",
    second: "секунда",
    selectedDateDescription: "Избрана дата: {date}",
    selectedRangeDescription: "Избран диапазон: {startDate} до {endDate}",
    selectedTimeDescription: "Избрано време: {time}",
    startDate: "Начална дата",
    timeZoneName: "часова зона",
    weekday: "ден от седмицата",
    year: "година",
  },
  "cs-CZ": {
    calendar: "Kalendář",
    day: "den",
    dayPeriod: "část dne",
    endDate: "Konečné datum",
    era: "letopočet",
    hour: "hodina",
    minute: "minuta",
    month: "měsíc",
    second: "sekunda",
    selectedDateDescription: "Vybrané datum: {date}",
    selectedRangeDescription: "Vybrané období: {startDate} až {endDate}",
    selectedTimeDescription: "Vybraný čas: {time}",
    startDate: "Počáteční datum",
    timeZoneName: "časové pásmo",
    weekday: "den v týdnu",
    year: "rok",
  },
  "da-DK": {
    calendar: "Kalender",
    day: "dag",
    dayPeriod: "AM/PM",
    endDate: "Slutdato",
    era: "æra",
    hour: "time",
    minute: "minut",
    month: "måned",
    second: "sekund",
    selectedDateDescription: "Valgt dato: {date}",
    selectedRangeDescription: "Valgt interval: {startDate} til {endDate}",
    selectedTimeDescription: "Valgt tidspunkt: {time}",
    startDate: "Startdato",
    timeZoneName: "tidszone",
    weekday: "ugedag",
    year: "år",
  },
  "de-DE": {
    calendar: "Kalender",
    day: "Tag",
    dayPeriod: "Tageshälfte",
    endDate: "Enddatum",
    era: "Epoche",
    hour: "Stunde",
    minute: "Minute",
    month: "Monat",
    second: "Sekunde",
    selectedDateDescription: "Ausgewähltes Datum: {date}",
    selectedRangeDescription: "Ausgewählter Bereich: {startDate} bis {endDate}",
    selectedTimeDescription: "Ausgewählte Zeit: {time}",
    startDate: "Anfangsdatum",
    timeZoneName: "Zeitzone",
    weekday: "Wochentag",
    year: "Jahr",
  },
  "el-GR": {
    calendar: "Ημερολόγιο",
    day: "ημέρα",
    dayPeriod: "π.μ./μ.μ.",
    endDate: "Ημερομηνία λήξης",
    era: "περίοδος",
    hour: "ώρα",
    minute: "λεπτό",
    month: "μήνας",
    second: "δευτερόλεπτο",
    selectedDateDescription: "Επιλεγμένη ημερομηνία: {date}",
    selectedRangeDescription: "Επιλεγμένο εύρος: {startDate} έως {endDate}",
    selectedTimeDescription: "Επιλεγμένη ώρα: {time}",
    startDate: "Ημερομηνία έναρξης",
    timeZoneName: "ζώνη ώρας",
    weekday: "καθημερινή",
    year: "έτος",
  },
  "en-US": {
    era: "era",
    year: "year",
    month: "month",
    day: "day",
    hour: "hour",
    minute: "minute",
    second: "second",
    dayPeriod: "AM/PM",
    calendar: "Calendar",
    startDate: "Start Date",
    endDate: "End Date",
    weekday: "day of the week",
    timeZoneName: "time zone",
    selectedDateDescription: "Selected Date: {date}",
    selectedRangeDescription: "Selected Range: {startDate} to {endDate}",
    selectedTimeDescription: "Selected Time: {time}",
  },
  "es-ES": {
    calendar: "Calendario",
    day: "día",
    dayPeriod: "a. m./p. m.",
    endDate: "Fecha final",
    era: "era",
    hour: "hora",
    minute: "minuto",
    month: "mes",
    second: "segundo",
    selectedDateDescription: "Fecha seleccionada: {date}",
    selectedRangeDescription: "Rango seleccionado: {startDate} a {endDate}",
    selectedTimeDescription: "Hora seleccionada: {time}",
    startDate: "Fecha de inicio",
    timeZoneName: "zona horaria",
    weekday: "día de la semana",
    year: "año",
  },
  "et-EE": {
    calendar: "Kalender",
    day: "päev",
    dayPeriod: "enne/pärast lõunat",
    endDate: "Lõppkuupäev",
    era: "ajastu",
    hour: "tund",
    minute: "minut",
    month: "kuu",
    second: "sekund",
    selectedDateDescription: "Valitud kuupäev: {date}",
    selectedRangeDescription: "Valitud vahemik: {startDate} kuni {endDate}",
    selectedTimeDescription: "Valitud aeg: {time}",
    startDate: "Alguskuupäev",
    timeZoneName: "ajavöönd",
    weekday: "nädalapäev",
    year: "aasta",
  },
  "fi-FI": {
    calendar: "Kalenteri",
    day: "päivä",
    dayPeriod: "vuorokaudenaika",
    endDate: "Päättymispäivä",
    era: "aikakausi",
    hour: "tunti",
    minute: "minuutti",
    month: "kuukausi",
    second: "sekunti",
    selectedDateDescription: "Valittu päivämäärä: {date}",
    selectedRangeDescription: "Valittu aikaväli: {startDate} – {endDate}",
    selectedTimeDescription: "Valittu aika: {time}",
    startDate: "Alkamispäivä",
    timeZoneName: "aikavyöhyke",
    weekday: "viikonpäivä",
    year: "vuosi",
  },
  "fr-FR": {
    calendar: "Calendrier",
    day: "jour",
    dayPeriod: "cadran",
    endDate: "Date de fin",
    era: "ère",
    hour: "heure",
    minute: "minute",
    month: "mois",
    second: "seconde",
    selectedDateDescription: "Date sélectionnée : {date}",
    selectedRangeDescription: "Plage sélectionnée : {startDate} au {endDate}",
    selectedTimeDescription: "Heure choisie : {time}",
    startDate: "Date de début",
    timeZoneName: "fuseau horaire",
    weekday: "jour de la semaine",
    year: "année",
  },
  "he-IL": {
    calendar: "לוח שנה",
    day: "יום",
    dayPeriod: "לפנה״צ/אחה״צ",
    endDate: "תאריך סיום",
    era: "תקופה",
    hour: "שעה",
    minute: "דקה",
    month: "חודש",
    second: "שנייה",
    selectedDateDescription: "תאריך נבחר: {date}",
    selectedRangeDescription: "טווח נבחר: {startDate} עד {endDate}",
    selectedTimeDescription: "זמן נבחר: {time}",
    startDate: "תאריך התחלה",
    timeZoneName: "אזור זמן",
    weekday: "יום בשבוע",
    year: "שנה",
  },
  "hr-HR": {
    calendar: "Kalendar",
    day: "dan",
    dayPeriod: "AM/PM",
    endDate: "Datum završetka",
    era: "era",
    hour: "sat",
    minute: "minuta",
    month: "mjesec",
    second: "sekunda",
    selectedDateDescription: "Odabrani datum: {date}",
    selectedRangeDescription: "Odabrani raspon: {startDate} do {endDate}",
    selectedTimeDescription: "Odabrano vrijeme: {time}",
    startDate: "Datum početka",
    timeZoneName: "vremenska zona",
    weekday: "dan u tjednu",
    year: "godina",
  },
  "hu-HU": {
    calendar: "Naptár",
    day: "nap",
    dayPeriod: "napszak",
    endDate: "Befejező dátum",
    era: "éra",
    hour: "óra",
    minute: "perc",
    month: "hónap",
    second: "másodperc",
    selectedDateDescription: "Kijelölt dátum: {date}",
    selectedRangeDescription: "Kijelölt tartomány: {startDate}–{endDate}",
    selectedTimeDescription: "Kijelölt idő: {time}",
    startDate: "Kezdő dátum",
    timeZoneName: "időzóna",
    weekday: "hét napja",
    year: "év",
  },
  "it-IT": {
    calendar: "Calendario",
    day: "giorno",
    dayPeriod: "AM/PM",
    endDate: "Data finale",
    era: "era",
    hour: "ora",
    minute: "minuto",
    month: "mese",
    second: "secondo",
    selectedDateDescription: "Data selezionata: {date}",
    selectedRangeDescription: "Intervallo selezionato: da {startDate} a {endDate}",
    selectedTimeDescription: "Ora selezionata: {time}",
    startDate: "Data iniziale",
    timeZoneName: "fuso orario",
    weekday: "giorno della settimana",
    year: "anno",
  },
  "ja-JP": {
    calendar: "カレンダー",
    day: "日",
    dayPeriod: "午前/午後",
    endDate: "終了日",
    era: "時代",
    hour: "時",
    minute: "分",
    month: "月",
    second: "秒",
    selectedDateDescription: "選択した日付 : {date}",
    selectedRangeDescription: "選択範囲 : {startDate} から {endDate}",
    selectedTimeDescription: "選択した時間 : {time}",
    startDate: "開始日",
    timeZoneName: "タイムゾーン",
    weekday: "曜日",
    year: "年",
  },
  "ko-KR": {
    calendar: "달력",
    day: "일",
    dayPeriod: "오전/오후",
    endDate: "종료 날짜",
    era: "연호",
    hour: "시",
    minute: "분",
    month: "월",
    second: "초",
    selectedDateDescription: "선택 일자: {date}",
    selectedRangeDescription: "선택 범위: {startDate} ~ {endDate}",
    selectedTimeDescription: "선택 시간: {time}",
    startDate: "시작 날짜",
    timeZoneName: "시간대",
    weekday: "요일",
    year: "년",
  },
  "lt-LT": {
    calendar: "Kalendorius",
    day: "diena",
    dayPeriod: "iki pietų / po pietų",
    endDate: "Pabaigos data",
    era: "era",
    hour: "valanda",
    minute: "minutė",
    month: "mėnuo",
    second: "sekundė",
    selectedDateDescription: "Pasirinkta data: {date}",
    selectedRangeDescription: "Pasirinktas intervalas: nuo {startDate} iki {endDate}",
    selectedTimeDescription: "Pasirinktas laikas: {time}",
    startDate: "Pradžios data",
    timeZoneName: "laiko juosta",
    weekday: "savaitės diena",
    year: "metai",
  },
  "lv-LV": {
    calendar: "Kalendārs",
    day: "diena",
    dayPeriod: "priekšpusdienā/pēcpusdienā",
    endDate: "Beigu datums",
    era: "ēra",
    hour: "stundas",
    minute: "minūtes",
    month: "mēnesis",
    second: "sekundes",
    selectedDateDescription: "Atlasītais datums: {date}",
    selectedRangeDescription: "Atlasītais diapazons: no {startDate} līdz {endDate}",
    selectedTimeDescription: "Atlasītais laiks: {time}",
    startDate: "Sākuma datums",
    timeZoneName: "laika josla",
    weekday: "nedēļas diena",
    year: "gads",
  },
  "nb-NO": {
    calendar: "Kalender",
    day: "dag",
    dayPeriod: "a.m./p.m.",
    endDate: "Sluttdato",
    era: "tidsalder",
    hour: "time",
    minute: "minutt",
    month: "måned",
    second: "sekund",
    selectedDateDescription: "Valgt dato: {date}",
    selectedRangeDescription: "Valgt område: {startDate} til {endDate}",
    selectedTimeDescription: "Valgt tid: {time}",
    startDate: "Startdato",
    timeZoneName: "tidssone",
    weekday: "ukedag",
    year: "år",
  },
  "nl-NL": {
    calendar: "Kalender",
    day: "dag",
    dayPeriod: "a.m./p.m.",
    endDate: "Einddatum",
    era: "tijdperk",
    hour: "uur",
    minute: "minuut",
    month: "maand",
    second: "seconde",
    selectedDateDescription: "Geselecteerde datum: {date}",
    selectedRangeDescription: "Geselecteerd bereik: {startDate} tot {endDate}",
    selectedTimeDescription: "Geselecteerde tijd: {time}",
    startDate: "Startdatum",
    timeZoneName: "tijdzone",
    weekday: "dag van de week",
    year: "jaar",
  },
  "pl-PL": {
    calendar: "Kalendarz",
    day: "dzień",
    dayPeriod: "rano / po południu / wieczorem",
    endDate: "Data końcowa",
    era: "era",
    hour: "godzina",
    minute: "minuta",
    month: "miesiąc",
    second: "sekunda",
    selectedDateDescription: "Wybrana data: {date}",
    selectedRangeDescription: "Wybrany zakres: {startDate} do {endDate}",
    selectedTimeDescription: "Wybrany czas: {time}",
    startDate: "Data początkowa",
    timeZoneName: "strefa czasowa",
    weekday: "dzień tygodnia",
    year: "rok",
  },
  "pt-BR": {
    calendar: "Calendário",
    day: "dia",
    dayPeriod: "AM/PM",
    endDate: "Data final",
    era: "era",
    hour: "hora",
    minute: "minuto",
    month: "mês",
    second: "segundo",
    selectedDateDescription: "Data selecionada: {date}",
    selectedRangeDescription: "Intervalo selecionado: {startDate} a {endDate}",
    selectedTimeDescription: "Hora selecionada: {time}",
    startDate: "Data inicial",
    timeZoneName: "fuso horário",
    weekday: "dia da semana",
    year: "ano",
  },
  "pt-PT": {
    calendar: "Calendário",
    day: "dia",
    dayPeriod: "am/pm",
    endDate: "Data de Término",
    era: "era",
    hour: "hora",
    minute: "minuto",
    month: "mês",
    second: "segundo",
    selectedDateDescription: "Data selecionada: {date}",
    selectedRangeDescription: "Intervalo selecionado: {startDate} a {endDate}",
    selectedTimeDescription: "Hora selecionada: {time}",
    startDate: "Data de Início",
    timeZoneName: "fuso horário",
    weekday: "dia da semana",
    year: "ano",
  },
  "ro-RO": {
    calendar: "Calendar",
    day: "zi",
    dayPeriod: "a.m/p.m.",
    endDate: "Dată final",
    era: "eră",
    hour: "oră",
    minute: "minut",
    month: "lună",
    second: "secundă",
    selectedDateDescription: "Dată selectată: {date}",
    selectedRangeDescription: "Interval selectat: de la {startDate} până la {endDate}",
    selectedTimeDescription: "Ora selectată: {time}",
    startDate: "Dată început",
    timeZoneName: "fus orar",
    weekday: "ziua din săptămână",
    year: "an",
  },
  "ru-RU": {
    calendar: "Календарь",
    day: "день",
    dayPeriod: "AM/PM",
    endDate: "Дата окончания",
    era: "эра",
    hour: "час",
    minute: "минута",
    month: "месяц",
    second: "секунда",
    selectedDateDescription: "Выбранная дата: {date}",
    selectedRangeDescription: "Выбранный диапазон: с {startDate} по {endDate}",
    selectedTimeDescription: "Выбранное время: {time}",
    startDate: "Дата начала",
    timeZoneName: "часовой пояс",
    weekday: "день недели",
    year: "год",
  },
  "sk-SK": {
    calendar: "Kalendár",
    day: "deň",
    dayPeriod: "AM/PM",
    endDate: "Dátum ukončenia",
    era: "letopočet",
    hour: "hodina",
    minute: "minúta",
    month: "mesiac",
    second: "sekunda",
    selectedDateDescription: "Vybratý dátum: {date}",
    selectedRangeDescription: "Vybratý rozsah: od {startDate} do {endDate}",
    selectedTimeDescription: "Vybratý čas: {time}",
    startDate: "Dátum začatia",
    timeZoneName: "časové pásmo",
    weekday: "deň týždňa",
    year: "rok",
  },
  "sl-SI": {
    calendar: "Koledar",
    day: "dan",
    dayPeriod: "dop/pop",
    endDate: "Datum konca",
    era: "doba",
    hour: "ura",
    minute: "minuta",
    month: "mesec",
    second: "sekunda",
    selectedDateDescription: "Izbrani datum: {date}",
    selectedRangeDescription: "Izbrano območje: {startDate} do {endDate}",
    selectedTimeDescription: "Izbrani čas: {time}",
    startDate: "Datum začetka",
    timeZoneName: "časovni pas",
    weekday: "dan v tednu",
    year: "leto",
  },
  "sr-SP": {
    calendar: "Kalendar",
    day: "дан",
    dayPeriod: "пре подне/по подне",
    endDate: "Datum završetka",
    era: "ера",
    hour: "сат",
    minute: "минут",
    month: "месец",
    second: "секунд",
    selectedDateDescription: "Izabrani datum: {date}",
    selectedRangeDescription: "Izabrani opseg: od {startDate} do {endDate}",
    selectedTimeDescription: "Izabrano vreme: {time}",
    startDate: "Datum početka",
    timeZoneName: "временска зона",
    weekday: "дан у недељи",
    year: "година",
  },
  "sv-SE": {
    calendar: "Kalender",
    day: "dag",
    dayPeriod: "fm/em",
    endDate: "Slutdatum",
    era: "era",
    hour: "timme",
    minute: "minut",
    month: "månad",
    second: "sekund",
    selectedDateDescription: "Valt datum: {date}",
    selectedRangeDescription: "Valt intervall: {startDate} till {endDate}",
    selectedTimeDescription: "Vald tid: {time}",
    startDate: "Startdatum",
    timeZoneName: "tidszon",
    weekday: "veckodag",
    year: "år",
  },
  "tr-TR": {
    calendar: "Takvim",
    day: "gün",
    dayPeriod: "ÖÖ/ÖS",
    endDate: "Bitiş Tarihi",
    era: "çağ",
    hour: "saat",
    minute: "dakika",
    month: "ay",
    second: "saniye",
    selectedDateDescription: "Seçilen Tarih: {date}",
    selectedRangeDescription: "Seçilen Aralık: {startDate} - {endDate}",
    selectedTimeDescription: "Seçilen Zaman: {time}",
    startDate: "Başlangıç Tarihi",
    timeZoneName: "saat dilimi",
    weekday: "haftanın günü",
    year: "yıl",
  },
  "uk-UA": {
    calendar: "Календар",
    day: "день",
    dayPeriod: "дп/пп",
    endDate: "Дата завершення",
    era: "ера",
    hour: "година",
    minute: "хвилина",
    month: "місяць",
    second: "секунда",
    selectedDateDescription: "Вибрана дата: {date}",
    selectedRangeDescription: "Вибраний діапазон: {startDate} — {endDate}",
    selectedTimeDescription: "Вибраний час: {time}",
    startDate: "Дата початку",
    timeZoneName: "часовий пояс",
    weekday: "день тижня",
    year: "рік",
  },
  "zh-CN": {
    calendar: "日历",
    day: "日",
    dayPeriod: "上午/下午",
    endDate: "结束日期",
    era: "纪元",
    hour: "小时",
    minute: "分钟",
    month: "月",
    second: "秒",
    selectedDateDescription: "选定的日期：{date}",
    selectedRangeDescription: "选定的范围：{startDate} 至 {endDate}",
    selectedTimeDescription: "选定的时间：{time}",
    startDate: "开始日期",
    timeZoneName: "时区",
    weekday: "工作日",
    year: "年",
  },
  "zh-TW": {
    calendar: "日曆",
    day: "日",
    dayPeriod: "上午/下午",
    endDate: "結束日期",
    era: "纪元",
    hour: "小时",
    minute: "分钟",
    month: "月",
    second: "秒",
    selectedDateDescription: "選定的日期：{date}",
    selectedRangeDescription: "選定的範圍：{startDate} 至 {endDate}",
    selectedTimeDescription: "選定的時間：{time}",
    startDate: "開始日期",
    timeZoneName: "时区",
    weekday: "工作日",
    year: "年",
  },
};
