export const COMBOBOX_INTL_MESSAGES = {
  "ar-AE": {
    triggerLabel: "عرض المقترحات",
    countAnnouncement: "{optionCount, plural, one {# خيار} other {# خيارات}} متاحة.",
    focusAnnouncement: "{optionText}{isSelected, select, true {, محدد} other {}}",
    listboxLabel: "مقترحات",
    selectedAnnouncement: "{optionText}، محدد",
  },
  "bg-BG": {
    triggerLabel: "Покажи предложения",
    countAnnouncement: "{optionCount, plural, one {# опция} other {# опции}} на разположение.",
    focusAnnouncement: "{optionText}{isSelected, select, true {, избрани} other {}}",
    listboxLabel: "Предложения",
    selectedAnnouncement: "{optionText}, избрани",
  },
  "cs-CZ": {
    triggerLabel: "Zobrazit doporučení",
    countAnnouncement:
      "K dispozici {optionCount, plural, one {je # možnost} other {jsou/je # možnosti/-í}}.",
    focusAnnouncement: "{optionText}{isSelected, select, true { (vybráno)} other {}}",
    listboxLabel: "Návrhy",
    selectedAnnouncement: "{optionText}, vybráno",
  },
  "da-DK": {
    triggerLabel: "Vis forslag",
    countAnnouncement:
      "{optionCount, plural, one {# mulighed tilgængelig} other {# muligheder tilgængelige}}.",
    focusAnnouncement: "{optionText}{isSelected, select, true {, valgt} other {}}",
    listboxLabel: "Forslag",
    selectedAnnouncement: "{optionText}, valgt",
  },
  "de-DE": {
    triggerLabel: "Empfehlungen anzeigen",
    countAnnouncement: "{optionCount, plural, one {# Option} other {# Optionen}} verfügbar.",
    focusAnnouncement: "{optionText}{isSelected, select, true {, ausgewählt} other {}}",
    listboxLabel: "Empfehlungen",
    selectedAnnouncement: "{optionText}, ausgewählt",
  },
  "el-GR": {
    triggerLabel: "Προβολή προτάσεων",
    countAnnouncement: "{optionCount, plural, one {# επιλογή} other {# επιλογές }} διαθέσιμες.",
    focusAnnouncement: "{optionText}{isSelected, select, true {, επιλεγμένο} other {}}",
    listboxLabel: "Προτάσεις",
    selectedAnnouncement: "{optionText}, επιλέχθηκε",
  },
  "en-US": {
    focusAnnouncement: "{optionText}{isSelected, select, true {, selected} other {}}",
    countAnnouncement: "{optionCount, plural, one {# option} other {# options}} available.",
    selectedAnnouncement: "{optionText}, selected",
    triggerLabel: "Show suggestions",
    listboxLabel: "Suggestions",
  },
  "es-ES": {
    triggerLabel: "Mostrar sugerencias",
    countAnnouncement: "{optionCount, plural, one {# opción} other {# opciones}} disponible(s).",
    focusAnnouncement: "{optionText}{isSelected, select, true {, seleccionado} other {}}",
    listboxLabel: "Sugerencias",
    selectedAnnouncement: "{optionText}, seleccionado",
  },
  "et-EE": {
    triggerLabel: "Kuva soovitused",
    countAnnouncement: "{optionCount, plural, one {# valik} other {# valikud}} saadaval.",
    focusAnnouncement: "{optionText}{isSelected, select, true {, valitud} other {}}",
    listboxLabel: "Soovitused",
    selectedAnnouncement: "{optionText}, valitud",
  },
  "fi-FI": {
    triggerLabel: "Näytä ehdotukset",
    countAnnouncement:
      "{optionCount, plural, one {# vaihtoehto} other {# vaihtoehdot}} saatavilla.",
    focusAnnouncement: "{optionText}{isSelected, select, true {, valittu} other {}}",
    listboxLabel: "Ehdotukset",
    selectedAnnouncement: "{optionText}, valittu",
  },
  "fr-FR": {
    triggerLabel: "Afficher les suggestions",
    countAnnouncement: "{optionCount, plural, one {# option} other {# options}} disponible(s).",
    focusAnnouncement: "{optionText}{isSelected, select, true {, sélectionné(s)} other {}}",
    listboxLabel: "Suggestions",
    selectedAnnouncement: "{optionText}, sélectionné",
  },
  "he-IL": {
    triggerLabel: "הצג הצעות",
    countAnnouncement: "{optionCount, plural, one {אפשרות #} other {# אפשרויות}} במצב זמין.",
    focusAnnouncement: "{optionText}{isSelected, select, true {, נבחר} other {}}",
    listboxLabel: "הצעות",
    selectedAnnouncement: "{optionText}, נבחר",
  },
  "hr-HR": {
    triggerLabel: "Prikaži prijedloge",
    countAnnouncement: "Dostupno još: {optionCount, plural, one {# opcija} other {# opcije/a}}.",
    focusAnnouncement: "{optionText}{isSelected, select, true {, odabranih} other {}}",
    listboxLabel: "Prijedlozi",
    selectedAnnouncement: "{optionText}, odabrano",
  },
  "hu-HU": {
    triggerLabel: "Javaslatok megjelenítése",
    countAnnouncement:
      "{optionCount, plural, one {# lehetőség} other {# lehetőség}} áll rendelkezésre.",
    focusAnnouncement: "{optionText}{isSelected, select, true {, kijelölve} other {}}",
    listboxLabel: "Javaslatok",
    selectedAnnouncement: "{optionText}, kijelölve",
  },
  "it-IT": {
    triggerLabel: "Mostra suggerimenti",
    countAnnouncement:
      "{optionCount, plural, one {# opzione disponibile} other {# opzioni disponibili}}.",
    focusAnnouncement: "{optionText}{isSelected, select, true {, selezionato} other {}}",
    listboxLabel: "Suggerimenti",
    selectedAnnouncement: "{optionText}, selezionato",
  },
  "ja-JP": {
    triggerLabel: "候補を表示",
    countAnnouncement:
      "{optionCount, plural, one {# 個のオプション} other {# 個のオプション}}を利用できます。",
    focusAnnouncement: "{optionText}{isSelected, select, true {、選択済み} other {}}",
    listboxLabel: "候補",
    selectedAnnouncement: "{optionText}、選択済み",
  },
  "ko-KR": {
    triggerLabel: "제안 사항 표시",
    countAnnouncement:
      "{optionCount, plural, one {#개 옵션} other {#개 옵션}}을 사용할 수 있습니다.",
    focusAnnouncement: "{optionText}{isSelected, select, true {, 선택됨} other {}}",
    listboxLabel: "제안",
    selectedAnnouncement: "{optionText}, 선택됨",
  },
  "lt-LT": {
    triggerLabel: "Rodyti pasiūlymus",
    countAnnouncement: "Yra {optionCount, plural, one {# parinktis} other {# parinktys (-ių)}}.",
    focusAnnouncement: "{optionText}{isSelected, select, true {, pasirinkta} other {}}",
    listboxLabel: "Pasiūlymai",
    selectedAnnouncement: "{optionText}, pasirinkta",
  },
  "lv-LV": {
    triggerLabel: "Rādīt ieteikumus",
    countAnnouncement:
      "Pieejamo opciju skaits: {optionCount, plural, one {# opcija} other {# opcijas}}.",
    focusAnnouncement: "{optionText}{isSelected, select, true {, atlasīta} other {}}",
    listboxLabel: "Ieteikumi",
    selectedAnnouncement: "{optionText}, atlasīta",
  },
  "nb-NO": {
    triggerLabel: "Vis forslag",
    countAnnouncement: "{optionCount, plural, one {# alternativ} other {# alternativer}} finnes.",
    focusAnnouncement: "{optionText}{isSelected, select, true {, valgt} other {}}",
    listboxLabel: "Forslag",
    selectedAnnouncement: "{optionText}, valgt",
  },
  "nl-NL": {
    triggerLabel: "Suggesties weergeven",
    countAnnouncement: "{optionCount, plural, one {# optie} other {# opties}} beschikbaar.",
    focusAnnouncement: "{optionText}{isSelected, select, true {, geselecteerd} other {}}",
    listboxLabel: "Suggesties",
    selectedAnnouncement: "{optionText}, geselecteerd",
  },
  "pl-PL": {
    triggerLabel: "Wyświetlaj sugestie",
    countAnnouncement:
      "dostępna/dostępne(-nych) {optionCount, plural, one {# opcja} other {# opcje(-i)}}.",
    focusAnnouncement: "{optionText}{isSelected, select, true {, wybrano} other {}}",
    listboxLabel: "Sugestie",
    selectedAnnouncement: "{optionText}, wybrano",
  },
  "pt-BR": {
    triggerLabel: "Mostrar sugestões",
    countAnnouncement: "{optionCount, plural, one {# opção} other {# opções}} disponível.",
    focusAnnouncement: "{optionText}{isSelected, select, true {, selecionado} other {}}",
    listboxLabel: "Sugestões",
    selectedAnnouncement: "{optionText}, selecionado",
  },
  "pt-PT": {
    triggerLabel: "Apresentar sugestões",
    countAnnouncement: "{optionCount, plural, one {# opção} other {# opções}} disponível.",
    focusAnnouncement: "{optionText}{isSelected, select, true {, selecionado} other {}}",
    listboxLabel: "Sugestões",
    selectedAnnouncement: "{optionText}, selecionado",
  },
  "ro-RO": {
    triggerLabel: "Afișare sugestii",
    countAnnouncement: "{optionCount, plural, one {# opțiune} other {# opțiuni}} disponibile.",
    focusAnnouncement: "{optionText}{isSelected, select, true {, selectat} other {}}",
    listboxLabel: "Sugestii",
    selectedAnnouncement: "{optionText}, selectat",
  },
  "ru-RU": {
    triggerLabel: "Показать предложения",
    countAnnouncement: "{optionCount, plural, one {# параметр} other {# параметров}} доступно.",
    focusAnnouncement: "{optionText}{isSelected, select, true {, выбранными} other {}}",
    listboxLabel: "Предложения",
    selectedAnnouncement: "{optionText}, выбрано",
  },
  "sk-SK": {
    triggerLabel: "Zobraziť návrhy",
    countAnnouncement: "{optionCount, plural, one {# možnosť} other {# možnosti/-í}} k dispozícii.",
    focusAnnouncement: "{optionText}{isSelected, select, true {, vybraté} other {}}",
    listboxLabel: "Návrhy",
    selectedAnnouncement: "{optionText}, vybraté",
  },
  "sl-SI": {
    triggerLabel: "Prikaži predloge",
    countAnnouncement: "Na voljo je {optionCount, plural, one {# opcija} other {# opcije}}.",
    focusAnnouncement: "{optionText}{isSelected, select, true {, izbrano} other {}}",
    listboxLabel: "Predlogi",
    selectedAnnouncement: "{optionText}, izbrano",
  },
  "sr-SP": {
    triggerLabel: "Prikaži predloge",
    countAnnouncement: "Dostupno još: {optionCount, plural, one {# opcija} other {# opcije/a}}.",
    focusAnnouncement: "{optionText}{isSelected, select, true {, izabranih} other {}}",
    listboxLabel: "Predlozi",
    selectedAnnouncement: "{optionText}, izabrano",
  },
  "sv-SE": {
    triggerLabel: "Visa förslag",
    countAnnouncement:
      "{optionCount, plural, one {# alternativ} other {# alternativ}} tillgängliga.",
    focusAnnouncement: "{optionText}{isSelected, select, true {, valda} other {}}",
    listboxLabel: "Förslag",
    selectedAnnouncement: "{optionText}, valda",
  },
  "tr-TR": {
    triggerLabel: "Önerileri göster",
    countAnnouncement:
      "{optionCount, plural, one {# seçenek} other {# seçenekler}} kullanılabilir.",
    focusAnnouncement: "{optionText}{isSelected, select, true {, seçildi} other {}}",
    listboxLabel: "Öneriler",
    selectedAnnouncement: "{optionText}, seçildi",
  },
  "uk-UA": {
    triggerLabel: "Показати пропозиції",
    countAnnouncement: "{optionCount, plural, one {# параметр} other {# параметри(-ів)}} доступно.",
    focusAnnouncement: "{optionText}{isSelected, select, true {, вибрано} other {}}",
    listboxLabel: "Пропозиції",
    selectedAnnouncement: "{optionText}, вибрано",
  },
  "zh-CN": {
    triggerLabel: "显示建议",
    countAnnouncement: "有 {optionCount, plural, one {# 个选项} other {# 个选项}}可用。",
    focusAnnouncement: "{optionText}{isSelected, select, true {, 已选择} other {}}",
    listboxLabel: "建议",
    selectedAnnouncement: "{optionText}, 已选择",
  },
  "zh-TW": {
    triggerLabel: "顯示建議",
    countAnnouncement: "{optionCount, plural, one {# 選項} other {# 選項}} 可用。",
    focusAnnouncement: "{optionText}{isSelected, select, true {, 已選取} other {}}",
    listboxLabel: "建議",
    selectedAnnouncement: "{optionText}, 已選取",
  },
};
