name: Format & Lint Files

on:
  pull_request:
    branches:
      - main
    paths:
      - "**.js"
      - "**.jsx"
      - "**.ts"
      - "**.tsx"
      - "**.cjs"
      - "**.json"
  push:
    branches:
      - main

jobs:
  biome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: 1.5.2

      - name: Run Biome
        run: biome ci .
